version: latest
services:
  Web-Video-Download:
    image: kmb32123/youtube-dl-server
    volumes:
      - ./youtube-dl/download:/youtube-dl
    ports:
      - 8081:8080
    restart: unless-stopped
networks: {}
